# Generated by Django 3.1.7 on 2021-05-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='half_centuries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='hundreds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='total_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='total_runs',
            field=models.IntegerField(default=0),
        ),
    ]
