# Generated by Django 3.1.7 on 2021-05-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20210515_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='highest_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='total_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teams.team'),
        ),
    ]
