# Generated by Django 3.1.7 on 2021-05-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20210516_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='player_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
