# Generated by Django 3.1.7 on 2021-05-17 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20210516_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_number', models.PositiveIntegerField(unique=True)),
                ('match_stadium', models.CharField(max_length=255)),
                ('match_location', models.CharField(max_length=255)),
                ('match_tournament', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('teams', models.ManyToManyField(to='teams.Team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
