# Generated by Django 3.1.7 on 2021-05-18 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20210517_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={},
        ),
        migrations.RemoveField(
            model_name='matches',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='match_location',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='match_number',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='match_stadium',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='match_tournament',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='teams',
        ),
        migrations.AlterField(
            model_name='matches',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('tied', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('result', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='teams.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='teams.team')),
            ],
        ),
    ]
