# Generated by Django 3.1.7 on 2021-05-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20210518_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team1',
            new_name='team_one',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2',
            new_name='team_two',
        ),
    ]
