# Generated by Django 3.1.7 on 2021-05-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20210518_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
    ]
