# Generated by Django 3.1.7 on 2021-05-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20210518_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='points',
            name='tied',
        ),
        migrations.AddField(
            model_name='match',
            name='id',
            field=models.AutoField(auto_created=True, default=11, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
